# Generated by Django 5.0 on 2025-11-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_game_id', models.CharField(max_length=100, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('game_time', models.DateTimeField()),
                ('bookmaker_name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('home_team_moneyline', models.IntegerField(blank=True, null=True)),
                ('away_team_moneyline', models.IntegerField(blank=True, null=True)),
                ('home_team_spread', models.FloatField(blank=True, null=True)),
                ('away_team_spread', models.FloatField(blank=True, null=True)),
                ('home_team_spread_price', models.IntegerField(blank=True, null=True)),
                ('away_team_spread_price', models.IntegerField(blank=True, null=True)),
                ('total_over', models.FloatField(blank=True, null=True)),
                ('total_over_price', models.IntegerField(blank=True, null=True)),
                ('total_under', models.FloatField(blank=True, null=True)),
                ('total_under_price', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['game_time'],
            },
        ),
    ]
