# Generated by Django 5.0 on 2025-11-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_score',
        ),
    ]
