# Generated by Django 5.0 on 2025-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_game_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("season", models.IntegerField()),
                ("week", models.IntegerField(blank=True, null=True)),
                ("season_type", models.CharField(max_length=20)),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                ("game_date", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.CharField(blank=True, max_length=50, null=True)),
                ("venue", models.CharField(blank=True, max_length=200, null=True)),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("neutral_site", models.BooleanField(default=False)),
                ("conference_game", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["game_date", "start_time"],
            },
        ),
    ]
